name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "requirements.txt"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Streamlit Cloud
        run: |
          streamlit hello
